# Generated by Django 2.2.4 on 2019-10-11 13:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=50, unique=True)),
                ('farm_address', models.CharField(max_length=100)),
                ('farm_description', models.CharField(max_length=300)),
                ('farm_logo_address', models.CharField(max_length=100)),
                ('farm_phonenumber', models.BigIntegerField(blank=True, default=0)),
                ('farm_contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('vedio_address', models.CharField(max_length=400)),
                ('pic_address', models.CharField(max_length=400)),
                ('item_description', models.CharField(blank=True, max_length=600)),
                ('item_price', models.IntegerField()),
                ('item_num_available', models.IntegerField()),
                ('item_guarantee', models.IntegerField()),
                ('item_benefit', models.CharField(max_length=200)),
                ('item_period', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataserver.FarmUser')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=50)),
                ('option_A', models.CharField(max_length=10)),
                ('option_B', models.CharField(max_length=10)),
                ('option_C', models.CharField(max_length=10)),
                ('option_D', models.CharField(max_length=10)),
                ('Answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='WxUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_openid', models.CharField(default='', max_length=50, unique=True)),
                ('user_address', models.CharField(blank=True, default='', max_length=100)),
                ('user_phonenumber', models.BigIntegerField(blank=True, default=0)),
                ('user_nickname', models.CharField(default='', max_length=50)),
                ('user_addressee', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=50)),
                ('region_address', models.CharField(max_length=100)),
                ('num_rows', models.IntegerField()),
                ('num_lines', models.IntegerField()),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataserver.FarmUser')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataserver.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_num', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('order_effect_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_is_active', models.BooleanField(default=True)),
                ('order_price_paid', models.IntegerField()),
                ('order_quantity', models.IntegerField()),
                ('order_price_origin', models.IntegerField()),
                ('order_tree_ip', models.CharField(max_length=50)),
                ('oder_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataserver.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.CharField(max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataserver.Item')),
                ('wxuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataserver.WxUser')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cer_type', models.CharField(max_length=50)),
                ('cer_name', models.CharField(max_length=50)),
                ('cer_pic_address', models.CharField(max_length=50)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataserver.FarmUser')),
            ],
        ),
    ]
