# Generated by Django 2.2.5 on 2019-11-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0004_auto_20191020_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_address', models.CharField(max_length=80)),
                ('video_class', models.CharField(default='', max_length=20)),
                ('video_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_guarantee',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_num_available',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_item',
        ),
        migrations.AddField(
            model_name='certification',
            name='cer_discription',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='farmuser',
            name='farm_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmuser',
            name='farm_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='item_guaranteed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='item_num_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='item_num_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_benifits',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='order_buyernickname',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='order_delivered',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_guaranteed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_timespanse',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='question_class',
            field=models.CharField(default='无', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='question_rank',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_reward',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='region',
            name='status',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='user_avatar',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='user_gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male'), ('null', 'null')], default='null', max_length=10),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='user_membership',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wxuser',
            name='user_region',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price_origin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_A',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_B',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_C',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_D',
            field=models.CharField(max_length=20),
        ),
    ]
