# Generated by Django 2.2.5 on 2019-11-06 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0005_auto_20191101_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='vedio_address',
            new_name='video_address',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_class',
            new_name='question_category',
        ),
    ]
