# Generated by Django 2.2.5 on 2019-11-19 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0006_auto_20191106_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
