# Generated by Django 2.2.5 on 2019-12-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0009_auto_20191203_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_farm',
        ),
    ]
