# Generated by Django 2.2.5 on 2019-12-03 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0010_remove_order_order_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_farm',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='dataserver.FarmUser'),
        ),
    ]
