# Generated by Django 2.2.5 on 2019-12-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0011_order_order_farm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_farm',
        ),
    ]
