# Generated by Django 2.2.5 on 2019-12-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0013_prepay_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prepay_order',
            old_name='itme_id',
            new_name='item_id',
        ),
    ]
