# Generated by Django 2.2.5 on 2019-12-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0014_auto_20191218_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepay_order',
            name='varified',
            field=models.BooleanField(default=False),
        ),
    ]
