# Generated by Django 2.2.5 on 2019-12-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0017_auto_20191219_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, unique=True),
        ),
    ]
