# Generated by Django 2.2.5 on 2019-12-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0018_auto_20191219_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_imageUrl',
            field=models.CharField(default='', max_length=50),
        ),
    ]
