# Generated by Django 2.2.5 on 2019-12-30 03:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0019_order_order_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectiveOrder',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('companyname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('phonenumber', models.IntegerField(blank=True)),
                ('wxid', models.CharField(blank=True, max_length=20)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='region',
            name='id',
        ),
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='GiftCode',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('itemId', models.IntegerField()),
                ('is_used', models.BooleanField(default=False)),
                ('tree_ip', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataserver.CollectiveOrder')),
            ],
        ),
    ]
