# Generated by Django 2.2.5 on 2019-12-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0020_auto_20191230_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmuser',
            name='latitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='farmuser',
            name='longitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
