# Generated by Django 2.2.5 on 2019-12-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0021_auto_20191230_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmuser',
            name='latitude',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='farmuser',
            name='longitude',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
