# Generated by Django 2.2.5 on 2020-01-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0022_auto_20191230_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varify_failed',
            fields=[
                ('out_trade_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('sign', models.CharField(max_length=50)),
                ('noncestr', models.CharField(max_length=50)),
                ('openid', models.CharField(max_length=40)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('item_id', models.IntegerField()),
                ('deliver_address', models.CharField(default='', max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('buyernickname', models.CharField(default='', max_length=20)),
                ('postsign', models.CharField(default='', max_length=50)),
                ('varified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='message_from_farm',
            field=models.CharField(default='', max_length=80),
        ),
    ]
