# Generated by Django 2.2.5 on 2020-01-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0023_auto_20200102_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varify_failed',
            name='buyernickname',
        ),
        migrations.RemoveField(
            model_name='varify_failed',
            name='deliver_address',
        ),
        migrations.RemoveField(
            model_name='varify_failed',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='varify_failed',
            name='noncestr',
        ),
        migrations.RemoveField(
            model_name='varify_failed',
            name='openid',
        ),
        migrations.RemoveField(
            model_name='varify_failed',
            name='postsign',
        ),
        migrations.RemoveField(
            model_name='varify_failed',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='varify_failed',
            name='varified',
        ),
        migrations.AddField(
            model_name='item',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
