# Generated by Django 2.2.5 on 2020-01-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0025_auto_20200105_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='message_from_farm',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
