# Generated by Django 2.2.5 on 2020-01-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0026_auto_20200105_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_num',
            field=models.CharField(default='', max_length=15),
        ),
    ]
