# Generated by Django 2.2.5 on 2020-01-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0028_auto_20200105_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name_rec',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='prepay_order',
            name='name_rec',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_num',
            field=models.CharField(default='', max_length=22),
        ),
    ]
