# Generated by Django 2.2.5 on 2020-01-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0030_auto_20200106_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='MchInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mch_id', models.CharField(max_length=20)),
                ('mch_key', models.CharField(max_length=50)),
                ('appid', models.CharField(max_length=20)),
                ('secret', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ip_line',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='ip_row',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='collectiveorder',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=1),
        ),
    ]
