# Generated by Django 2.2.5 on 2020-01-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0032_auto_20200110_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmuser',
            name='short',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='farm_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
