# Generated by Django 2.2.5 on 2020-01-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0033_auto_20200114_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_benefit',
            new_name='benefit',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_buyernickname',
            new_name='buyernickname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_deliver_address',
            new_name='deliver_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_delivered',
            new_name='delivered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_effect_time',
            new_name='effect_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_guaranteed',
            new_name='guaranteed',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_imageUrl',
            new_name='imageUrl',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_is_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_num',
            new_name='num',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_postsign',
            new_name='postsign',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_price_origin',
            new_name='price_origin',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_price_paid',
            new_name='price_paid',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_timespanse',
            new_name='timespanse',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_tree_ip',
            new_name='tree_ip',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_wxuser',
            new_name='wxuser',
        ),
    ]
