# Generated by Django 2.2.5 on 2020-01-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0034_auto_20200114_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='m_word',
            field=models.CharField(default='', max_length=5),
        ),
    ]
