# Generated by Django 2.2.5 on 2020-03-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataserver', '0036_auto_20200305_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxuser',
            name='user_avatar',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
