# Generated by Django 2.2.5 on 2020-03-05 13:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataserver', '0036_auto_20200305_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZxItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=100)),
                ('category', models.CharField(default='', max_length=100)),
                ('video_address', models.CharField(max_length=400)),
                ('pic_address', models.CharField(max_length=400)),
                ('item_description', models.CharField(blank=True, max_length=600)),
                ('item_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('item_num_total', models.IntegerField(default=0)),
                ('item_num_sold', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('unit', models.CharField(default='', max_length=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dataserver.FarmUser')),
            ],
        ),
        migrations.CreateModel(
            name='ZxPrepay_Order',
            fields=[
                ('out_trade_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('sign', models.CharField(max_length=50)),
                ('noncestr', models.CharField(max_length=50)),
                ('openid', models.CharField(max_length=40)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('item_id', models.IntegerField()),
                ('deliver_address', models.CharField(default='', max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('varified', models.BooleanField(default=False)),
                ('phone_num', models.CharField(default='', max_length=30)),
                ('name_rec', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ZxUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_openid', models.CharField(default='', max_length=50, unique=True)),
                ('user_gender', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('null', 'null')], default='null', max_length=10)),
                ('user_avatar', models.CharField(blank=True, default='', max_length=50)),
                ('user_nickname', models.CharField(default='', max_length=50)),
                ('user_address', models.CharField(blank=True, default='', max_length=100)),
                ('user_phonenumber', models.BigIntegerField(blank=True, default=0)),
                ('user_addressee', models.CharField(default='', max_length=50)),
                ('user_membership', models.IntegerField(default=0)),
                ('user_region', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ZxVarify_failed',
            fields=[
                ('out_trade_no', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('sign', models.CharField(max_length=50)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ZxOrder',
            fields=[
                ('num', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('farm_name', models.CharField(blank=True, default='', max_length=30)),
                ('deliver_address', models.CharField(default='', max_length=50)),
                ('effect_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('price_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantity', models.IntegerField(default=1)),
                ('price_origin', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('imageUrl', models.CharField(default='', max_length=50)),
                ('phone_num', models.CharField(default='', max_length=30)),
                ('name_rec', models.CharField(blank=True, default='', max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zxserver.ZxItem')),
                ('wxuser', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='zxserver.ZxUser')),
            ],
        ),
        migrations.CreateModel(
            name='ZxComments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField(default=0)),
                ('comment_text', models.CharField(max_length=100)),
                ('comment_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('zxuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zxserver.ZxUser')),
            ],
        ),
    ]
