# Generated by Django 2.2.5 on 2020-03-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxserver', '0002_auto_20200310_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='zxcomments',
            name='user_avatar',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='zxcomments',
            name='user_nickname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
