# Generated by Django 2.2.5 on 2020-03-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxserver', '0004_auto_20200316_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zxorder',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='zxprepay_order',
            name='captain',
        ),
        migrations.AddField(
            model_name='zxorder',
            name='captain_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='zxprepay_order',
            name='captain_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
