# Generated by Django 2.2.5 on 2020-03-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxserver', '0005_auto_20200316_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zxorder',
            name='captain_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='zxprepay_order',
            name='captain_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
