# Generated by Django 2.2.5 on 2020-03-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxserver', '0006_auto_20200316_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='zxorder',
            name='deliver_time',
            field=models.CharField(default='', max_length=30),
        ),
    ]
