# Generated by Django 2.2.5 on 2020-03-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxserver', '0007_zxorder_deliver_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='zxprepay_order',
            name='deliver_time',
            field=models.CharField(default='', max_length=30),
        ),
    ]
