# Generated by Django 2.2.5 on 2020-03-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxserver', '0008_zxprepay_order_deliver_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='zxuser',
            name='current_captain_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
