# Generated by Django 2.2.5 on 2020-03-24 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zxserver', '0009_zxuser_current_captain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captain',
            name='zxuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zxserver.ZxUser', unique=True),
        ),
    ]
