# Generated by Django 2.2.5 on 2020-03-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxserver', '0012_auto_20200324_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='zxcomments',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
