# Generated by Django 2.2.5 on 2020-04-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxserver', '0013_zxcomments_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='captain',
            name='dis_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
