# Generated by Django 2.2.5 on 2020-04-07 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zxserver', '0014_captain_dis_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invitecode', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('phonenumber', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='captain',
            name='manager',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='zxserver.CapManager'),
            preserve_default=False,
        ),
    ]
