# Generated by Django 2.2.5 on 2020-04-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxserver', '0015_auto_20200407_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='capmanager',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
    ]
