# Generated by Django 2.2.5 on 2020-04-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxserver', '0016_capmanager_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='capmanager',
            name='commission',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='captain',
            name='commission',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zxitem',
            name='unit',
            field=models.CharField(default='', max_length=15),
        ),
    ]
