# Generated by Django 2.2.5 on 2020-04-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zxserver', '0017_auto_20200413_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='zxcomments',
            name='genre',
            field=models.IntegerField(choices=[(1, 'comments'), (2, 'purches')], default=1),
        ),
    ]
