# Generated by Django 2.2.5 on 2020-06-17 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataserver', '0037_auto_20200310_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(default='', max_length=30, unique=True)),
                ('pic', models.FileField(unique=True, upload_to='statics/pic/')),
                ('video', models.FileField(unique=True, upload_to='statics/video/')),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=80)),
                ('phonenumber', models.BigIntegerField(blank=True, default=0, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('role', models.CharField(default='farmuser', max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('farm', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='dataserver.FarmUser')),
            ],
        ),
    ]
